[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "your_package_name"
version = "0.1.0"
description = "Example project"
authors = [{ name="Your Name", email="you@example.com" }]
dependencies = ["requests"]
